### ISSUE TITLE
Network should allow to pull all wallets

### ISSUE THREAD

**Issue by t-izbassar** [zold-io/java-api#11]
The `Network` interface should contain method, that will allow pulling all wallets.
```java
public interface Network {
    // Pull all wallets from the network.
    Wallets wallets();
}
```

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@6ac9e0a3-eadb-45bf-b051-800033971ed4, thread: pool-522-thread-1
com.zerocracy.radars.github.ThrottledComments[76] java.lang.IllegalStateException: Can't post an identical message to zold-io/java-api#11: @llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue
```

[0.24.9](https://github.com/zerocracy/farm): Issue: zold-io/java-api#11, Action: `opened`

**Comment by llorllale** [comment]
@t-izbassar why would you need that?

**Comment by t-izbassar** [comment]
@llorllale it will be used to have the initial state of up-to-date `Wallets`. Also, it might be useful when we want to clear the current `Wallets` for some reasons and pull them back. Well, maybe it should be done in `Wallets` but I think the method to pull them all should belong to `Network`.

**Comment by llorllale** [comment]
@t-izbassar if we add a ctor `WalletsIn(Iterable<Wallet>)` then we could do:

```java
final Wallets updated = new WalletsIn(
    new Mapped<>(
        w -> w.merge(network.pull(w.id())),
        wallets
    )
);
```

**Comment by t-izbassar** [comment]
@llorllale make sense, thanks.

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@6ac9e0a3-eadb-45bf-b051-800033971ed4, thread: pool-821-thread-1
com.zerocracy.pm.Claims[122] java.lang.IllegalStateException: Duplicate claims are not allowed in [CAZUREFND](https://www.0crat.com/p/CAZUREFND), can't add this XML to 5 existing ones (Close job;{job=gh:zold-io/java-api#11, reason=GitHub issue was closed},Close job;{job=gh:zold-io/java-api#7, reason=GitHub issue was closed},Close job;{job=gh:zold-io/java-api#7, reason=GitHub issue was closed},Close job;{job=gh:zold-io/java-api#8, reason=GitHub issue was closed},Close job;{job=gh:zold-io/java-api#8, reason=GitHub issue was closed}):
<?xml version="1.0" encoding="UTF-8"?>
<claim id="1850508796">
   <created>2018-07-04T05:01:10.459Z</created>
   <type>Close job</type>
   <token>github;zold-io/java-api;11</token>
   <author>t-izbassar</author>
   <params>
      <param name="job">gh:zold-io/java-api#11</param>
      <param name="reason">GitHub issue was closed</param>
   </params>
   <until>2018-07-04T05:16:10.461Z</until>
</claim>

```

[0.24.9](https://github.com/zerocracy/farm): Issue: zold-io/java-api#11, Action: `closed`

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@6ac9e0a3-eadb-45bf-b051-800033971ed4, thread: pool-820-thread-1
com.zerocracy.pm.Claims[122] java.lang.IllegalStateException: Duplicate claims are not allowed in [CAZUREFND](https://www.0crat.com/p/CAZUREFND), can't add this XML to 6 existing ones (Close job;{job=gh:zold-io/java-api#11, reason=GitHub issue was closed},Close job;{job=gh:zold-io/java-api#11, reason=GitHub issue was closed},Close job;{job=gh:zold-io/java-api#7, reason=GitHub issue was closed},Close job;{job=gh:zold-io/java-api#7, reason=GitHub issue was closed},Close job;{job=gh:zold-io/java-api#8, reason=GitHub issue was closed},Close job;{job=gh:zold-io/java-api#8, reason=GitHub issue was closed}):
<?xml version="1.0" encoding="UTF-8"?>
<claim id="1850508797">
   <created>2018-07-04T05:01:17.026Z</created>
   <type>Close job</type>
   <token>github;zold-io/java-api;11</token>
   <author>t-izbassar</author>
   <params>
      <param name="job">gh:zold-io/java-api#11</param>
      <param name="reason">GitHub issue was closed</param>
   </params>
   <until>2018-07-04T05:16:17.028Z</until>
</claim>

```

[0.24.9](https://github.com/zerocracy/farm): Issue: zold-io/java-api#11, Action: `closed`

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@6ac9e0a3-eadb-45bf-b051-800033971ed4, thread: pool-823-thread-1
com.zerocracy.radars.github.ThrottledComments[76] java.lang.IllegalStateException: Can't post an identical message to zold-io/java-api#11: @llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue
```

[0.24.9](https://github.com/zerocracy/farm): Issue: zold-io/java-api#11, Action: `reopened`

**Comment by t-izbassar** [comment]
@llorllale but from where we will receive this `Iterable<Wallet>` with which we can merge it? Right now we will need to pull them one by one.

**Comment by 0crat** [comment]
Job `gh:zold-io/java-api#11` is not assigned, can't get performer

**Comment by 0crat** [comment]
Job `gh:zold-io/java-api#11` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by llorllale** [comment]
@t-izbassar the REST API does not provide an endpoint for pulling a list of wallets.

The `Iterable<Wallet>` will be `Mapped` in this case:

```java
final Wallets updated = new WalletsIn(
    new Mapped<>(
        w -> w.merge(network.pull(w.id())),
        wallets
    )
);
```

**Comment by llorllale** [comment]
@t-izbassar if the wallets in a directory are removed you should be able to obtain an the updated version from the network itself by pulling them. It is assumed that you previously pushed all changes in your wallets to the network.

**Comment by t-izbassar** [comment]
@llorllale thanks for clarifications. I also have read the white paper and understand many things better now.

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@b79d11cf-1a5a-4d28-94a7-6a09e9474515, thread: pool-922-thread-1
com.zerocracy.pm.Claims[122] java.lang.IllegalStateException: Duplicate claims are not allowed in [CAZUREFND](https://www.0crat.com/p/CAZUREFND), can't add this XML to 3 existing ones (Close job;{job=gh:zold-io/java-api#11, reason=GitHub issue was closed},Close job;{job=gh:zold-io/java-api#11, reason=GitHub issue was closed},Ping;{}):
<?xml version="1.0" encoding="UTF-8"?>
<claim id="1870734326">
   <created>2018-07-06T07:19:46.388Z</created>
   <type>Close job</type>
   <token>github;zold-io/java-api;11</token>
   <author>t-izbassar</author>
   <params>
      <param name="job">gh:zold-io/java-api#11</param>
      <param name="reason">GitHub issue was closed</param>
   </params>
   <until>2018-07-06T07:34:46.39Z</until>
</claim>

```

[0.25.1](https://github.com/zerocracy/farm): Issue: zold-io/java-api#11, Action: `closed`

**Comment by 0crat** [comment]
Job `gh:zold-io/java-api#11` is not assigned, can't get performer

**Comment by 0crat** [comment]
Job `gh:zold-io/java-api#11` is not assigned, can't get performer

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@b79d11cf-1a5a-4d28-94a7-6a09e9474515, thread: AsyncFlush-1
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 1 error(s) in XML document: -1:-1: Duplicate unique value [gh:zold-io/java-api#11] declared for identity constraint of element "blanks".
```

[0.25.1](https://github.com/zerocracy/farm): CID: [1870734326](https://www.0crat.com/CAZUREFND/1870734326), Type: "Close job", Author: "t-izbassar"
