### ISSUE TITLE
Wallet.java:131-134: Implement merge method. This should...

### ISSUE THREAD

**Issue by 0pdd** [zold-io/java-api#16]
The puzzle `6-af7c6ffd` from #6 has to be resolved:

https://github.com/zold-io/java-api/blob/55c445ee86bcac8453fb2efacfc396330d580345/src/main/java/io/zold/api/Wallet.java#L131-L134

The puzzle was created by rultor on 04-Jul-18. 

Estimate: 30 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@7029763d-567a-43e6-8426-2f46b4b74955, thread: pool-637-thread-1
com.zerocracy.radars.github.ThrottledComments[76] java.lang.IllegalStateException: Can't post an identical message to zold-io/java-api#16: @llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue
```

[0.24.10](https://github.com/zerocracy/farm): Issue: zold-io/java-api#16, Action: `opened`

**Comment by llorllale** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/zold-io/java-api/issues/16#issuecomment-402844512))

@llorllale Job [#16](https://github.com/zold-io/java-api/issues/16) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#16](https://github.com/zold-io/java-api/issues/16) assigned to @llorllale[/z](https://www.0crat.com/u/llorllale), here is [why](https://www.0crat.com/footprint/CAZUREFND/1862052109); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by llorllale** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zold-io/java-api/issues/16#issuecomment-402882393))

@llorllale The user @llorllale[/z](https://www.0crat.com/u/llorllale) resigned from [#16](https://github.com/zold-io/java-api/issues/16), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
The job [#16](https://github.com/zold-io/java-api/issues/16) assigned to @t-izbassar[/z](https://www.0crat.com/u/t-izbassar), here is [why](https://www.0crat.com/footprint/CAZUREFND/1870014418); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@t-izbassar[/z](https://www.0crat.com/u/t-izbassar) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by t-izbassar** [comment]
@0crat wait for #17 as the transaction order is important for this task.

**Comment by 0crat** [comment]
> @0crat wait for #17 as the transaction order is important for this task. ([here](https://github.com/zold-io/java-api/issues/16#issuecomment-404274856))

@t-izbassar The impediment for [#16](https://github.com/zold-io/java-api/issues/16) was registered successfully by @t-izbassar[/z](https://www.0crat.com/u/t-izbassar)

**Comment by t-izbassar** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zold-io/java-api/issues/16#issuecomment-408387736))

@t-izbassar The user @t-izbassar[/z](https://www.0crat.com/u/t-izbassar) resigned from [#16](https://github.com/zold-io/java-api/issues/16), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @t-izbassar[/z](https://www.0crat.com/u/t-izbassar)

**Comment by 0crat** [comment]
The job [#16](https://github.com/zold-io/java-api/issues/16) assigned to @vatavuk[/z](https://www.0crat.com/u/vatavuk), here is [why](https://www.0crat.com/footprint/CAZUREFND/2141856690); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by Vatavuk** [comment]
@0crat wait busy week

**Comment by 0crat** [comment]
> @0crat wait busy week ([here](https://github.com/zold-io/java-api/issues/16#issuecomment-410980985))

@Vatavuk The impediment for [#16](https://github.com/zold-io/java-api/issues/16) was registered successfully by @vatavuk[/z](https://www.0crat.com/u/vatavuk)

**Comment by 0pdd** [comment]
The puzzle `6-af7c6ffd` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#75](https://github.com/zold-io/java-api/issues/75), [#76](https://github.com/zold-io/java-api/issues/76) are still not solved.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @vatavuk[/z](https://www.0crat.com/u/vatavuk), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#16](https://github.com/zold-io/java-api/issues/16) is now out of scope

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @vatavuk[/z](https://www.0crat.com/u/vatavuk)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
