### ISSUE TITLE
Wallet.java:142-144: Implement ledger method. This should...

### ISSUE THREAD

**Issue by 0pdd** [zold-io/java-api#17]
The puzzle `6-2cc9aa8f` from #6 has to be resolved:

https://github.com/zold-io/java-api/blob/55c445ee86bcac8453fb2efacfc396330d580345/src/main/java/io/zold/api/Wallet.java#L142-L144

The puzzle was created by rultor on 04-Jul-18. 

Estimate: 30 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
I can't create GitHub labels `pdd`. Most likely I don't have necessary permissions to `zold-io/java-api` repository. Please, make sure @0pdd user is in the [list of collaborators](https://github.com/zold-io/java-api/settings/collaboration):

```Octokit::NotFound
POST https://api.github.com/repos/zold-io/java-api/labels: 404 - Not Found // See: https://developer.github.com/v3/issues/labels/#create-a-label
/app/vendor/bundle/ruby/2.3.0/gems/octokit-4.9.0/lib/octokit/response/raise_error.rb:16:in `on_complete'
/app/vendor/bundle/ruby/2.3.0/gems/faraday-0.15.2/lib/faraday/response.rb:9:in `block in call'
/app/vendor/bundle/ruby/2.3.0/gems/faraday-0.15.2/lib/faraday/response.rb:61:in `on_complete'
/app/vendor/bundle/ruby/2.3.0/gems/faraday-0.15.2/lib/faraday/response.rb:8:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/octokit-4.9.0/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
/app/vendor/bundle/ruby/2.3.0/gems/octokit-4.9.0/lib/octokit/middleware/follow_redirects.rb:61:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/faraday-0.15.2/lib/faraday/rack_builder.rb:143:in `build_response'
/app/vendor/bundle/ruby/2.3.0/gems/faraday-0.15.2/lib/faraday/connection.rb:387:in `run_request'
/app/vendor/bundle/ruby/2.3.0/gems/faraday-0.15.2/lib/faraday/connection.rb:175:in `post'
/app/vendor/bundle/ruby/2.3.0/gems/sawyer-0.8.1/lib/sawyer/agent.rb:94:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/octokit-4.9.0/lib/octokit/connection.rb:156:in `request'
/app/vendor/bundle/ruby/2.3.0/gems/octokit-4.9.0/lib/octokit/connection.rb:28:in `post'
/app/vendor/bundle/ruby/2.3.0/gems/octokit-4.9.0/lib/octokit/client/labels.rb:44:in `add_label'
/app/objects/github_tagged_tickets.rb:50:in `block in submit'
/app/objects/github_tagged_tickets.rb:50:in `each'
/app/objects/github_tagged_tickets.rb:50:in `submit'
/app/objects/commit_tickets.rb:38:in `submit'
/app/objects/emailed_tickets.rb:35:in `submit'
/app/objects/sentry_tickets.rb:46:in `submit'
/app/objects/puzzles.rb:91:in `block in expose'
/app/objects/puzzles.rb:82:in `loop'
/app/objects/puzzles.rb:82:in `expose'
/app/objects/puzzles.rb:33:in `deploy'
/app/objects/job.rb:38:in `proceed'
/app/objects/job_starred.rb:33:in `proceed'
/app/objects/job_recorded.rb:32:in `proceed'
/app/objects/job_emailed.rb:35:in `proceed'
/app/objects/job_commiterrors.rb:36:in `proceed'
/app/objects/job_detached.rb:48:in `exclusive'
/app/objects/job_detached.rb:36:in `block in proceed'
/app/objects/job_detached.rb:36:in `fork'
/app/objects/job_detached.rb:36:in `proceed'
/app/0pdd.rb:342:in `block in <top (required)>'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1634:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1634:in `block in compile!'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:992:in `block (3 levels) in route!'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1011:in `route_eval'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:992:in `block (2 levels) in route!'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1039:in `block in process_route'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1037:in `catch'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1037:in `process_route'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:990:in `block in route!'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:989:in `each'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:989:in `route!'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1096:in `block in dispatch!'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `block in invoke'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `catch'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `invoke'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1093:in `dispatch!'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:924:in `block in call!'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `block in invoke'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `catch'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `invoke'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:924:in `call!'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:913:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/rack-protection-2.0.1/lib/rack/protection/xss_header.rb:18:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/rack-protection-2.0.1/lib/rack/protection/path_traversal.rb:16:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/rack-protection-2.0.1/lib/rack/protection/json_csrf.rb:26:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/rack-protection-2.0.1/lib/rack/protection/base.rb:50:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/rack-protection-2.0.1/lib/rack/protection/base.rb:50:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/rack-protection-2.0.1/lib/rack/protection/frame_options.rb:31:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.5/lib/rack/logger.rb:15:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.5/lib/rack/common_logger.rb:33:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:231:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:224:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.5/lib/rack/head.rb:12:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.5/lib/rack/method_override.rb:22:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:194:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1957:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1501:in `block in call'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1728:in `synchronize'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1501:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.5/lib/rack/handler/webrick.rb:86:in `service'
/app/vendor/ruby-2.3.3/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
/app/vendor/ruby-2.3.3/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
/app/vendor/ruby-2.3.3/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'
```

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@7029763d-567a-43e6-8426-2f46b4b74955, thread: pool-644-thread-1
com.zerocracy.radars.github.ThrottledComments[76] java.lang.IllegalStateException: Can't post an identical message to zold-io/java-api#17: @llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue
```

[0.24.10](https://github.com/zerocracy/farm): Issue: zold-io/java-api#17, Action: `opened`

**Comment by llorllale** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/zold-io/java-api/issues/17#issuecomment-402844475))

@llorllale Job [#17](https://github.com/zold-io/java-api/issues/17) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#17](https://github.com/zold-io/java-api/issues/17) assigned to @llorllale[/z](https://www.0crat.com/u/llorllale), here is [why](https://www.0crat.com/footprint/CAZUREFND/1862047053); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by llorllale** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zold-io/java-api/issues/17#issuecomment-402882408))

@llorllale The user @llorllale[/z](https://www.0crat.com/u/llorllale) resigned from [#17](https://github.com/zold-io/java-api/issues/17), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0crat** [comment]
The job [#17](https://github.com/zold-io/java-api/issues/17) assigned to @t-izbassar[/z](https://www.0crat.com/u/t-izbassar), here is [why](https://www.0crat.com/footprint/CAZUREFND/1862369366); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@t-izbassar[/z](https://www.0crat.com/u/t-izbassar) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by t-izbassar** [comment]
@0crat wait for #30 to be merged

**Comment by 0crat** [comment]
> @0crat wait for #30 to be merged ([here](https://github.com/zold-io/java-api/issues/17#issuecomment-404273539))

@t-izbassar The impediment for [#17](https://github.com/zold-io/java-api/issues/17) was registered successfully by @t-izbassar[/z](https://www.0crat.com/u/t-izbassar)

**Comment by 0pdd** [comment]
The puzzle `6-2cc9aa8f` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@a9418e99-3af0-45e0-857b-f999e4ba8836, thread: pool-553-thread-1
com.zerocracy.pm.Claims[109] java.lang.IllegalStateException: Duplicate claims are not allowed in [CAZUREFND](https://www.0crat.com/p/CAZUREFND), can't add this XML to 2 existing ones (Close job;{job=gh:zold-io/java-api#17, reason=GitHub issue was closed};github;zold-io/java-api;17,Close job;{job=gh:zold-io/java-api#17, reason=GitHub issue was closed};github;zold-io/java-api;17):
<?xml version="1.0" encoding="UTF-8"?>
<claim id="1931962709">
   <created>2018-07-12T19:56:10.699Z</created>
   <type>Close job</type>
   <token>github;zold-io/java-api;17</token>
   <author>0pdd</author>
   <params>
      <param name="job">gh:zold-io/java-api#17</param>
      <param name="reason">GitHub issue was closed</param>
   </params>
   <until>2018-07-12T20:11:10.701Z</until>
</claim>

```

[0.25.7](https://github.com/zerocracy/farm): Issue: zold-io/java-api#17, Action: `closed`

**Comment by t-izbassar** [comment]
@0pdd fixed in #30.

**Comment by t-izbassar** [comment]
@0crat status

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@a9418e99-3af0-45e0-857b-f999e4ba8836, thread: pool-571-thread-1
com.zerocracy.pm.Claims[109] java.lang.IllegalStateException: Duplicate claims are not allowed in [CAZUREFND](https://www.0crat.com/p/CAZUREFND), can't add this XML to 5 existing ones (Check job status;{comment=404632001, job=gh:zold-io/java-api#17, issue=17, repo=zold-io/java-api};github;zold-io/java-api;17;404632001,Close job;{job=gh:zold-io/java-api#17, reason=GitHub issue was closed};github;zold-io/java-api;17,Close job;{job=gh:zold-io/java-api#17, reason=GitHub issue was closed};github;zold-io/java-api;17,Close job;{job=gh:zold-io/java-api#30, reason=GitHub issue was closed};github;zold-io/java-api;30,Close job;{job=gh:zold-io/java-api#30, reason=GitHub issue was closed};github;zold-io/java-api;30):
<?xml version="1.0" encoding="UTF-8"?>
<claim id="1931963719">
   <created>2018-07-12T19:57:36.095Z</created>
   <type>Check job status</type>
   <token>github;zold-io/java-api;17;404632001</token>
   <author>t-izbassar</author>
   <params>
      <param name="job">gh:zold-io/java-api#17</param>
      <param name="repo">zold-io/java-api</param>
      <param name="issue">17</param>
      <param name="comment">404632001</param>
   </params>
</claim>

```

[0.25.7](https://github.com/zerocracy/farm): Issue: zold-io/java-api#17, Comment: 404632001

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@a9418e99-3af0-45e0-857b-f999e4ba8836, thread: pool-571-thread-1
com.zerocracy.radars.github.ReSafe[80] java.io.IOException: java.lang.IllegalStateException: Duplicate claims are not allowed in [CAZUREFND](https://www.0crat.com/p/CAZUREFND), can't add this XML to 5 existing ones (Check job status;{comment=404632001, job=gh:zold-io/java-api#17, issue=17, repo=zold-io/java-api};github;zold-io/java-api;17;404632001,Close job;{job=gh:zold-io/java-api#17, reason=GitHub issue was closed};github;zold-io/java-api;17,Close job;{job=gh:zold-io/java-api#17, reason=GitHub issue was closed};github;zold-io/java-api;17,Close job;{job=gh:zold-io/java-api#30, reason=GitHub issue was closed};github;zold-io/java-api;30,Close job;{job=gh:zold-io/java-api#30, reason=GitHub issue was closed};github;zold-io/java-api;30):
<?xml version="1.0" encoding="UTF-8"?>
<claim id="1931963719">
   <created>2018-07-12T19:57:36.095Z</created>
   <type>Check job status</type>
   <token>github;zold-io/java-api;17;404632001</token>
   <author>t-izbassar</author>
   <params>
      <param name="job">gh:zold-io/java-api#17</param>
      <param name="repo">zold-io/java-api</param>
      <param name="issue">17</param>
      <param name="comment">404632001</param>
   </params>
</claim>

com.zerocracy.pm.Claims[109] java.lang.IllegalStateException: Duplicate claims are not allowed in [CAZUREFND](https://www.0crat.com/p/CAZUREFND), can't add this XML to 5 existing ones (Check job status;{comment=404632001, job=gh:zold-io/java-api#17, issue=17, repo=zold-io/java-api};github;zold-io/java-api;17;404632001,Close job;{job=gh:zold-io/java-api#17, reason=GitHub issue was closed};github;zold-io/java-api;17,Close job;{job=gh:zold-io/java-api#17, reason=GitHub issue was closed};github;zold-io/java-api;17,Close job;{job=gh:zold-io/java-api#30, reason=GitHub issue was closed};github;zold-io/java-api;30,Close job;{job=gh:zold-io/java-api#30, reason=GitHub issue was closed};github;zold-io/java-api;30):
<?xml version="1.0" encoding="UTF-8"?>
<claim id="1931963719">
   <created>2018-07-12T19:57:36.095Z</created>
   <type>Check job status</type>
   <token>github;zold-io/java-api;17;404632001</token>
   <author>t-izbassar</author>
   <params>
      <param name="job">gh:zold-io/java-api#17</param>
      <param name="repo">zold-io/java-api</param>
      <param name="issue">17</param>
      <param name="comment">404632001</param>
   </params>
</claim>

```

[0.25.7](https://github.com/zerocracy/farm): Issue: zold-io/java-api#17, Action: `created`

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zold-io/java-api/issues/17#issuecomment-404632001))

@t-izbassar This is what I know about this job in [CAZUREFND](https://www.0crat.com/p/CAZUREFND), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#17](https://github.com/zold-io/java-api/issues/17) is [in scope](http://www.zerocracy.com/policy.html#14) for 7days
  * The role is `DEV`
  * The job is assigned to @t-izbassar[/z](https://www.0crat.com/u/t-izbassar) for [7days](http://www.zerocracy.com/policy.html#8)
  * There is a monetary reward attached
  * @t-izbassar[/z](https://www.0crat.com/u/t-izbassar) will get 50% of their hourly rate for this job
  * The job has an [impediment](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @0pdd[/z](https://www.0crat.com/u/0pdd): This user reported the ticket
    * @llorllale[/z](https://www.0crat.com/u/llorllale): User was resigned from the ticket
  * Job [footprint](https://www.0crat.com/footprint/CAZUREFND?q=%7Bjob%3A%27gh%3Azold-io%2Fjava-api%2317%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by 0crat** [comment]
Quality review for [#17](https://github.com/zold-io/java-api/issues/17) already exists

**Comment by t-izbassar** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zold-io/java-api/issues/17#issuecomment-404635774))

@t-izbassar This is what I know about this job in [CAZUREFND](https://www.0crat.com/p/CAZUREFND), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#17](https://github.com/zold-io/java-api/issues/17) is [in scope](http://www.zerocracy.com/policy.html#14) for 7days
  * The role is `DEV`
  * The job is assigned to @t-izbassar[/z](https://www.0crat.com/u/t-izbassar) for [7days](http://www.zerocracy.com/policy.html#8)
  * There is a monetary reward attached
  * @t-izbassar[/z](https://www.0crat.com/u/t-izbassar) will get 50% of their hourly rate for this job
  * The job has an [impediment](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @0pdd[/z](https://www.0crat.com/u/0pdd): This user reported the ticket
    * @llorllale[/z](https://www.0crat.com/u/llorllale): User was resigned from the ticket
  * The job is waiting quality review verdict by @ypshenychka[/z](https://www.0crat.com/u/ypshenychka) for 58s
  * @t-izbassar[/z](https://www.0crat.com/u/t-izbassar) will receive 30 minutes after quality review
  * Job [footprint](https://www.0crat.com/footprint/CAZUREFND?q=%7Bjob%3A%27gh%3Azold-io%2Fjava-api%2317%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by t-izbassar** [comment]
@ypshenychka can you review this one as well? 0crat didn't put notification message again)

**Comment by ypshenychka** [comment]
@llorllale thank you!

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +46 point(s) just awarded to @t-izbassar[/z](https://www.0crat.com/u/t-izbassar)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0crat** [comment]
@t-izbassar[/z](https://www.0crat.com/u/t-izbassar) resigned from [#17](https://github.com/zold-io/java-api/issues/17), since the job is not in scope anymore

**Comment by 0crat** [comment]
The job [#17](https://github.com/zold-io/java-api/issues/17) is now out of scope
