### ISSUE TITLE
Upgrade qulice to 0.17.3

### ISSUE THREAD

**Issue by paulodamaso** [zold-io/java-api#18]
New qulice version brings following important changes:

- removal of `@author` tag (it is prohibited now)
- removal of `@version` tag (it is prohibited now)
- license header should start with `/*` instead of `/**` - this will fix problem with IntelliJ reporting it as a javadoc that is not attached to any class
- checkstyle validation performance improvement (speedup of ~ 10%)
- few minor formatting changes.
Please upgrade the qulice and fix the new problems found. It would be a good idea to upgrade now that the codebase have just a few classes.

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@b79d11cf-1a5a-4d28-94a7-6a09e9474515, thread: pool-747-thread-1
com.zerocracy.radars.github.ThrottledComments[76] java.lang.IllegalStateException: Can't post an identical message to zold-io/java-api#18: @llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue
```

[0.25.1](https://github.com/zerocracy/farm): Issue: zold-io/java-api#18, Action: `opened`

**Comment by 0crat** [comment]
The job [#18](https://github.com/zold-io/java-api/issues/18) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CAZUREFND/1940546428); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@4f505572-78c0-411f-9ee4-6020730f8c3b, thread: pool-190-thread-1
com.zerocracy.pm.Claims[109] java.lang.IllegalStateException: Duplicate claims are not allowed in [CAZUREFND](https://www.0crat.com/p/CAZUREFND), can't add this XML to 2 existing ones (Close job;{job=gh:zold-io/java-api#18, reason=GitHub issue was closed};github;zold-io/java-api;18,Close job;{job=gh:zold-io/java-api#18, reason=GitHub issue was closed};github;zold-io/java-api;18):
<?xml version="1.0" encoding="UTF-8"?>
<claim id="1980036433">
   <created>2018-07-17T00:33:30.472Z</created>
   <type>Close job</type>
   <token>github;zold-io/java-api;18</token>
   <author>paulodamaso</author>
   <params>
      <param name="job">gh:zold-io/java-api#18</param>
      <param name="reason">GitHub issue was closed</param>
   </params>
   <until>2018-07-17T00:48:30.475Z</until>
</claim>

```

[0.25.16](https://github.com/zerocracy/farm): Issue: zold-io/java-api#18, Action: `closed`

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
Job `gh:zold-io/java-api#18` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#18](https://github.com/zold-io/java-api/issues/18) is now out of scope

**Comment by ypshenychka** [comment]
@paulodamaso According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>Problem reporter and problem solver are two different persons; [see](https://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html#1.-keep-it-one-on-one)

Please confirm you'll try avoid such situations in future.

**Comment by llorllale** [comment]
@ypshenychka there seems to be a bug in 0crat then - it was automatically assigned to @paulodamaso [here](https://github.com/zold-io/java-api/issues/18#issuecomment-404730346)

**Comment by ypshenychka** [comment]
@llorllale I see. Probably there were no people available for this work or it's really a bug?

**Comment by ypshenychka** [comment]
@llorllale anyways I can't blame @paulodamaso here.
@paulodamaso please ignore my review comment.

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +46 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
