### ISSUE TITLE
How to sign?

### ISSUE THREAD

**Issue by t-izbassar** [zold-io/java-api#19]
According to the white paper, we should sign each transaction with RSA. For that, we need an RSA private key. Where to get it? Will it be generated for each wallet?

**Comment by llorllale** [comment]
@t-izbassar this RSA key will be managed by the user. The user can decide whether they want to use the same one for each of his wallets or different ones.

**Comment by llorllale** [comment]
@t-izbassar can we close this?

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@a9418e99-3af0-45e0-857b-f999e4ba8836, thread: AsyncFlush-3
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 1 error(s) in XML document: -1:-1: Duplicate unique value [gh:zold-io/java-api#19] declared for identity constraint of element "blanks".
```

[0.25.7](https://github.com/zerocracy/farm): CID: [1931329744](https://www.0crat.com/CAZUREFND/1931329744), Type: "Close job", Author: "t-izbassar"

**Comment by 0crat** [comment]
Job `gh:zold-io/java-api#19` is not assigned, can't get performer
