### ISSUE TITLE
WalletTest.java:43-46: CheckedScalar from 'cactoos' does...

### ISSUE THREAD

**Issue by 0pdd** [zold-io/java-api#34]
The puzzle `33-65714492` from #33 has to be resolved:

https://github.com/zold-io/java-api/blob/01791059c35ce1ac0476c20043f89db209f0ea5b/src/test/java/io/zold/api/WalletTest.java#L43-L46

The puzzle was created by George Aristy on 12-Jul-18. 

Estimate: 30 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
Job [#34](https://github.com/zold-io/java-api/issues/34) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@a9418e99-3af0-45e0-857b-f999e4ba8836, thread: pool-826-thread-1
com.zerocracy.radars.github.ThrottledComments[74] java.lang.IllegalStateException: Can't post an identical message to zold-io/java-api#34: @llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue
```

[0.25.7](https://github.com/zerocracy/farm): Issue: zold-io/java-api#34, Action: `opened`

**Comment by 0crat** [comment]
The job [#34](https://github.com/zold-io/java-api/issues/34) assigned to @t-izbassar[/z](https://www.0crat.com/u/t-izbassar), here is [why](https://www.0crat.com/footprint/CAZUREFND/1940556664); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@t-izbassar[/z](https://www.0crat.com/u/t-izbassar) this job was assigned to you 6days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @t-izbassar[/z](https://www.0crat.com/u/t-izbassar) resigned from [#34](https://github.com/zold-io/java-api/issues/34), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @t-izbassar[/z](https://www.0crat.com/u/t-izbassar)

**Comment by 0crat** [comment]
The job [#34](https://github.com/zold-io/java-api/issues/34) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CAZUREFND/2041328397); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by paulodamaso** [comment]
@llorllale What should I do here? It was decided in https://github.com/yegor256/cactoos/issues/933 that `cactoos` won't wrap `RuntimeExceptions`...

**Comment by paulodamaso** [comment]
@llorllale ping

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by llorllale** [comment]
@paulodamaso you made the right choice in your PR by not wrapping the exceptions

**Comment by paulodamaso** [comment]
@0crat wait for merge of #51

**Comment by 0crat** [comment]
> @0crat wait for merge of #51  ([here](https://github.com/zold-io/java-api/issues/34#issuecomment-409083154))

@paulodamaso The impediment for [#34](https://github.com/zold-io/java-api/issues/34) was registered successfully by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0pdd** [comment]
The puzzle `33-65714492` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@ff4e4492-afa3-49e7-b2e6-def21277e93d, thread: pool-69-thread-1
java.lang.NumberFormatException[65] java.lang.NumberFormatException: For input string: "2018-08-01T19:53:54.12Z"
```

[0.28.5](https://github.com/zerocracy/farm): Issue: zold-io/java-api#34, Action: `closed`

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@ff4e4492-afa3-49e7-b2e6-def21277e93d, thread: pool-67-thread-1
java.lang.NumberFormatException[65] java.lang.NumberFormatException: For input string: "2018-08-01T19:54:06.674Z"
```

[0.28.5](https://github.com/zerocracy/farm): Issue: zold-io/java-api#34, Action: `closed`

**Comment by paulodamaso** [comment]
@0crat out

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) the issue is closed not by @0pdd[/z](https://www.0crat.com/u/0pdd) (its creator); I won't close the order; please, re-open it and ask @0pdd[/z](https://www.0crat.com/u/0pdd) to close it

**Comment by paulodamaso** [comment]
@llorllale Please take a look, something went wrong

**Comment by llorllale** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/zold-io/java-api/issues/34#issuecomment-410027742))

@llorllale There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@4878718d-7092-46c7-892b-5800de759231, thread: AsyncProc-5
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 1 error(s) in XML document: -1:-1: Duplicate unique value [gh:zold-io/java-api#34] declared for identity constraint of element "verbosity".
```

[0.28.9](https://github.com/zerocracy/farm): CID: [2141841511](https://www.0crat.com/CAZUREFND/2141841511), Type: "Close job", Author: "llorllale"

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/zold-io/java-api/issues/34#issuecomment-410027742))

@llorllale The job [#34](https://github.com/zold-io/java-api/issues/34) is now out of scope

**Comment by paulodamaso** [comment]
@0crat status

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
