### ISSUE TITLE
RtNetwork.java:52-55: Implement scoring algorithm when...

### ISSUE THREAD

**Issue by 0pdd** [zold-io/java-api#40]
The puzzle `5-c56bb757` from #5 has to be resolved:

https://github.com/zold-io/java-api/blob/e7bf16247075ec2bb23081b61e1835fa44551621/src/main/java/io/zold/api/RtNetwork.java#L52-L55

The puzzle was created by Paulo Lobo on 19-Jul-18. 

Estimate: 30 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
The job [#40](https://github.com/zold-io/java-api/issues/40) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/CAZUREFND/2021936802); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by victornoel** [comment]
@0pdd implemented in #53

**Comment by 0pdd** [comment]
> @0pdd implemented in #53 

I see you're talking to me, but I can't reply since I'm not a chat bot.

**Comment by 0pdd** [comment]
The puzzle `5-c56bb757` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#61](https://github.com/zold-io/java-api/issues/61) is still not solved.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @victornoel[/z](https://www.0crat.com/u/victornoel), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#40](https://github.com/zold-io/java-api/issues/40) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0pdd** [comment]
@0pdd 4 puzzles [#81](https://github.com/zold-io/java-api/issues/81), [#82](https://github.com/zold-io/java-api/issues/82), [#83](https://github.com/zold-io/java-api/issues/83), [#84](https://github.com/zold-io/java-api/issues/84) are still not solved; solved: [#61](https://github.com/zold-io/java-api/issues/61).

**Comment by 0pdd** [comment]
@0pdd 4 puzzles [#116](https://github.com/zold-io/java-api/issues/116), [#117](https://github.com/zold-io/java-api/issues/117), [#82](https://github.com/zold-io/java-api/issues/82), [#84](https://github.com/zold-io/java-api/issues/84) are still not solved; solved: [#61](https://github.com/zold-io/java-api/issues/61), [#81](https://github.com/zold-io/java-api/issues/81), [#83](https://github.com/zold-io/java-api/issues/83).
