### ISSUE TITLE
RtTransaction.hashCode shouldn't directly delegate to String.hashCode

### ISSUE THREAD

**Issue by victornoel** [zold-io/java-api#43]
Current implementation of `RtTransaction.hashCode` directly delegate to `this.transaction.hashCode`, but this breaks the contract of `Object` that says that `equals` and `hashCode` should be coherent together.

In particular it means that a transaction and a plain string can have the same hash code, but calling `equals` on them will return false.

The solution is trivial: use `Objects.hash` that ensure this does not happen.

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@92cabbac-30a4-44cf-992a-e5c699798f8d, thread: pool-622-thread-1
com.zerocracy.radars.github.ThrottledComments[74] java.lang.IllegalStateException: Can't post an identical message to zold-io/java-api#43: @llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue
```

[0.26.4](https://github.com/zerocracy/farm): Issue: zold-io/java-api#43, Action: `opened`

**Comment by carlosmiranda** [comment]
@victornoel, you [say](https://github.com/zold-io/java-api/issues/43#issue-343387444)

> In particular it means that a transaction and a plain string can have the same hash code, but calling equals on them will return false.

This is incorrect. From the `hashCode` [contract](https://docs.oracle.com/javase/7/docs/api/java/lang/Object.html#hashCode()) (my emphasis in **bold**):

> The general contract of hashCode is:
> * Whenever it is invoked on the same object more than once during an execution of a Java application, the hashCode method must consistently return the same integer, provided no information used in equals comparisons on the object is modified. This integer need not remain consistent from one execution of an application to another execution of the same application.
> * If two objects are equal according to the equals(Object) method, then calling the hashCode method on each of the two objects must produce the same integer result.
> * **It is not required that if two objects are unequal according to the equals(java.lang.Object) method, then calling the hashCode method on each of the two objects must produce distinct integer results.** However, the programmer should be aware that producing distinct integer results for unequal objects may improve the performance of hash tables.

There may be other reasons why delegating to `String.hashCode` might not be a good idea, but right now `RtTransaction.hashCode` complies with the `hashCode` contract.

**Comment by victornoel** [comment]
Ok, I agree this is not violating the contract, but it is really cheap not to have this performance impact in that case. Why would we entertain the ambiguity just because we can?

**Comment by carlosmiranda** [comment]
@victornoel for the most part I'm just being pedantic about your reasoning :) I don't _disagree_ that we should change it, ultimately it's the decision to make by @llorllale .

**Comment by victornoel** [comment]
@carlosmiranda hehe, I would have done the same in your position ;)

**Comment by llorllale** [comment]
@victornoel I think it's fine the way it is for now, thanks

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
Job `gh:zold-io/java-api#43` is not assigned, can't get performer
