### ISSUE TITLE
Incorrect Network.push specification

### ISSUE THREAD

**Issue by victornoel** [zold-io/java-api#48]
In the process of solving #40, I am faced with a problem with the existing code.

The javadoc of `Network.push` says:
```java
    /**
     * Push the wallet to the network. The network will select the
     * remote node with the highest score (with a minimum of {@code 16}).
     * @param wallet The wallet
     */
    void push(Wallet wallet);
```

But I don't think that is correct: the papers talks about selecting nodes with high score and a minimum of 16 when paying taxes. This has nothing to do with pushing, which should be done to every known nodes (even though they can decide not to accept the wallet).

The concept of paying taxes and of pushing should be separated (it is the case in the ruby implementation).

Either `Wallet` should be responsible of paying taxes, or `Network` should.

I would be favour of letting `Network` do that simply because it would be best, design-wise, to have `Wallet` being ignorant of `Network` and `Remote`s matters. `Network` already manipulates both `Remote`s and `Wallet`s.

@llorllale what do you think?

@paulodamaso since you did create the `@todo`s I suppose you have maybe an opinion?

**Comment by victornoel** [comment]
@llorllale @paulodamaso ping :)

**Comment by paulodamaso** [comment]
@victornoel Sorry for the delay.

You are right, this javadoc is not correct. The pushing must have to be done to every known node, and its concept is separated of the paying taxes.

In my opinion `Network` should delegate these operations to `Remote` and `Wallet` as you suggested.

**Comment by victornoel** [comment]
@paulodamaso thanks for the feedback.

@llorllale I will go with the suggestion we agree on with @paulodamaso and we can discuss this in the PR if this is problematic.

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
Job `gh:zold-io/java-api#48` is not assigned, can't get performer

**Comment by llorllale** [comment]
@victornoel right, the javadoc needs to be fixed
