### ISSUE TITLE
CpTransaction.java:30-32: Implement the computation of...

### ISSUE THREAD

**Issue by 0pdd** [zold-io/java-api#54]
The puzzle `29-4f17ced3` from #29 has to be resolved:

https://github.com/zold-io/java-api/blob/72b9c483a598541c5923dcffaf05500492af3b74/src/main/java/io/zold/api/CpTransaction.java#L30-L32

The puzzle was created by Victor Noël on 25-Jul-18. 

Estimate: 30 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
Job [#54](https://github.com/zold-io/java-api/issues/54) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@bf4e29b1-3db5-439e-a1e9-0b7d0b7f3da4, thread: pool-461-thread-1
com.zerocracy.radars.github.ThrottledComments[74] java.lang.IllegalStateException: Can't post an identical message to zold-io/java-api#54: @llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue
```

[0.27.4](https://github.com/zerocracy/farm): Issue: zold-io/java-api#54, Action: `opened`

**Comment by 0crat** [comment]
The job [#54](https://github.com/zold-io/java-api/issues/54) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CAZUREFND/2141847569); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by paulodamaso** [comment]
@victornoel What would be "computation" of transaction? It is not mentioned by its terms anywhere in witepaper.

**Comment by victornoel** [comment]
@paulodamaso it is something that compute the string of the transaction, not the transaction itself. It's a computed transaction. When creating a new transaction, you need to define its string representation, and in particular it includes the signature based on the private RSA key of the wallet + some other things. It is described in the paper where the transaction string is described in Section 4, "Wallets".

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by paulodamaso** [comment]
@0crat wait for review on #63

**Comment by 0crat** [comment]
> @0crat wait for review on #63  ([here](https://github.com/zold-io/java-api/issues/54#issuecomment-411501833))

@paulodamaso The impediment for [#54](https://github.com/zold-io/java-api/issues/54) was registered successfully by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0pdd** [comment]
The puzzle `29-4f17ced3` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#73](https://github.com/zold-io/java-api/issues/73), [#74](https://github.com/zold-io/java-api/issues/74) are still not solved.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#54](https://github.com/zold-io/java-api/issues/54) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
