### ISSUE TITLE
Copies.java:35-41: The constructor of Copies should be...

### ISSUE THREAD

**Issue by 0pdd** [zold-io/java-api#56]
The puzzle `41-44da2a34` from #41 has to be resolved:

https://github.com/zold-io/java-api/blob/7002ecb9690f5ae24333dcf4d86bb8dbde22bf97/src/main/java/io/zold/api/Copies.java#L35-L41

The puzzle was created by Victor Noël on 23-Jul-18. 

Estimate: 30 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@d2e831bb-fcd8-41df-b5b6-0873f0280485, thread: pool-662-thread-1
com.zerocracy.radars.github.ThrottledComments[74] java.lang.IllegalStateException: Can't post an identical message to zold-io/java-api#56: @llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue
```

[0.27.4](https://github.com/zerocracy/farm): Issue: zold-io/java-api#56, Action: `opened`

**Comment by 0crat** [comment]
Job [#56](https://github.com/zold-io/java-api/issues/56) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#56](https://github.com/zold-io/java-api/issues/56) assigned to @vatavuk[/z](https://www.0crat.com/u/vatavuk), here is [why](https://www.0crat.com/footprint/CAZUREFND/2141852638); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by Vatavuk** [comment]
@0crat wait for a review in #60

**Comment by 0crat** [comment]
> @0crat wait for a review in #60  ([here](https://github.com/zold-io/java-api/issues/56#issuecomment-410981454))

@Vatavuk The impediment for [#56](https://github.com/zold-io/java-api/issues/56) was registered successfully by @vatavuk[/z](https://www.0crat.com/u/vatavuk)

**Comment by 0pdd** [comment]
The puzzle `41-44da2a34` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#79](https://github.com/zold-io/java-api/issues/79), [#80](https://github.com/zold-io/java-api/issues/80) are still not solved.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @vatavuk[/z](https://www.0crat.com/u/vatavuk), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#56](https://github.com/zold-io/java-api/issues/56) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @vatavuk[/z](https://www.0crat.com/u/vatavuk)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
