### ISSUE TITLE
WalletsIn.java:93-95: Create the new wallet in the path...

### ISSUE THREAD

**Issue by 0pdd** [zold-io/java-api#65]
The puzzle `12-1be65647` from #12 has to be resolved:

https://github.com/zold-io/java-api/blob/50f250cf1c8c59665d2f689f88a5a4c70e0774b1/src/main/java/io/zold/api/WalletsIn.java#L93-L95

The puzzle was created by rultor on 08-Aug-18. 

Estimate: 30 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@4257b3f8-8b2e-4f2e-b504-f3511a4994d0, thread: pool-134-thread-1
com.zerocracy.radars.github.ThrottledComments[74] java.lang.IllegalStateException: Can't post an identical message to zold-io/java-api#65: @llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue
```

[0.29.7](https://github.com/zerocracy/farm): Issue: zold-io/java-api#65, Action: `opened`

**Comment by 0crat** [comment]
Job [#65](https://github.com/zold-io/java-api/issues/65) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#65](https://github.com/zold-io/java-api/issues/65) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CAZUREFND/2210751434); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by paulodamaso** [comment]
@0crat wait fr #78

**Comment by 0crat** [comment]
> @0crat wait fr #78  ([here](https://github.com/zold-io/java-api/issues/65#issuecomment-413552536))

@paulodamaso The impediment for [#65](https://github.com/zold-io/java-api/issues/65) was registered successfully by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0pdd** [comment]
The puzzle `12-1be65647` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#85](https://github.com/zold-io/java-api/issues/85), [#86](https://github.com/zold-io/java-api/issues/86) are still not solved.

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by ypshenychka** [comment]
@llorllale No payment here as well

**Comment by paulodamaso** [comment]
@llorllale Ditto

**Comment by llorllale** [comment]
@0crat pay @ypshenychka 8min

**Comment by llorllale** [comment]
@0crat pay @paulodamaso 35min

**Comment by 0crat** [comment]
> @0crat pay @ypshenychka 8min ([here](https://github.com/zold-io/java-api/issues/65#issuecomment-444718928))

@llorllale Argument "@ypshenychka" doesn't match regex `\d+min`

**Comment by 0crat** [comment]
> @0crat pay @paulodamaso 35min ([here](https://github.com/zold-io/java-api/issues/65#issuecomment-444718967))

@llorllale Argument "@paulodamaso" doesn't match regex `\d+min`

**Comment by paulodamaso** [comment]
@llorllale ping

**Comment by llorllale** [comment]
@0crat pay 35min @paulodamaso

**Comment by llorllale** [comment]
@0crat pay 8min @ypshenychka

**Comment by 0crat** [comment]
> @0crat pay 35min @paulodamaso  ([here](https://github.com/zold-io/java-api/issues/65#issuecomment-447689604))

@llorllale The project is under-funded, you can't do it now, see [§49](http://www.zerocracy.com/policy.html#49)

**Comment by 0crat** [comment]
> @0crat pay 8min @ypshenychka  ([here](https://github.com/zold-io/java-api/issues/65#issuecomment-447689617))

@llorllale The project is under-funded, you can't do it now, see [§49](http://www.zerocracy.com/policy.html#49)
