### ISSUE TITLE
Documentation is inconsistent with Interfaces

### ISSUE THREAD

**Issue by t-izbassar** [zold-io/java-api#7]
The [README.md](https://github.com/zold-io/java-api/blob/master/README.md) is outdated. There is no `find` method in `Wallets.` Also no `pull` method in `Wallet.` The `Amount` interface does not exist.

With outdated documentation, it's hard to understand how the interfaces are intended to be used.

**Comment by 0crat** [comment]
The job [#7](https://github.com/zold-io/java-api/issues/7) assigned to @llorllale[/z](https://www.0crat.com/u/llorllale), here is [why](https://www.0crat.com/footprint/CAZUREFND/1842040690); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Job `gh:zold-io/java-api#7` already assigned to @llorllale, can't assign to @llorllale

**Comment by 0crat** [comment]
Job [#7](https://github.com/zold-io/java-api/issues/7) is already assigned to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @t-izbassar[/z](https://www.0crat.com/u/t-izbassar)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by llorllale** [comment]
@t-izbassar 

#### To find a wallet in `Wallets`
```java
final Wallet wallet = new Filtered<>(
    w -> "9999888877776666".equals(w.id()),
    wallets
).iterator().next();
```

#### To pull (and merge) wallet from the network:
```java
final Wallet merged = wallet.merge(
    network.pull(wallet.id())
);
```

Regarding `Amount`, I honestly don't see a need for it (yet). Seems like a bit of over-engineering to me, don't you think?

**Comment by t-izbassar** [comment]
@llorllale yes, I agree. Thanks for the update of documentation. Let's delete `Amoun` I guess. We can introduce it later.

**Comment by llorllale** [comment]
@t-izbassar see e5396bd908b3292637b8c899c6e0a5a1f7938cfc

Can we close this now?

**Comment by t-izbassar** [comment]
@llorllale sure. Thanks.

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@6ac9e0a3-eadb-45bf-b051-800033971ed4, thread: pool-806-thread-1
com.zerocracy.pm.Claims[122] java.lang.IllegalStateException: Duplicate claims are not allowed in [CAZUREFND](https://www.0crat.com/p/CAZUREFND), can't add this XML to 2 existing ones (Close job;{job=gh:zold-io/java-api#7, reason=GitHub issue was closed},Close job;{job=gh:zold-io/java-api#7, reason=GitHub issue was closed}):
<?xml version="1.0" encoding="UTF-8"?>
<claim id="1850466785">
   <created>2018-07-04T04:59:58.063Z</created>
   <type>Close job</type>
   <token>github;zold-io/java-api;7</token>
   <author>t-izbassar</author>
   <params>
      <param name="job">gh:zold-io/java-api#7</param>
      <param name="reason">GitHub issue was closed</param>
   </params>
   <until>2018-07-04T05:14:58.066Z</until>
</claim>

```

[0.24.9](https://github.com/zerocracy/farm): Issue: zold-io/java-api#7, Action: `closed`

**Comment by llorllale** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zold-io/java-api/issues/7#issuecomment-402882509))

@llorllale This is what I know about this job in [CAZUREFND](https://www.0crat.com/p/CAZUREFND), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#7](https://github.com/zold-io/java-api/issues/7) is [in scope](http://www.zerocracy.com/policy.html#14) for 2days
  * The role is `DEV`
  * The job is assigned to @llorllale[/z](https://www.0crat.com/u/llorllale) for [2days](http://www.zerocracy.com/policy.html#8)
  * There is a monetary reward attached
  * @llorllale[/z](https://www.0crat.com/u/llorllale) will get 50% of their hourly rate for this job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @t-izbassar[/z](https://www.0crat.com/u/t-izbassar): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/CAZUREFND?q=%7Bjob%3A%27gh%3Azold-io%2Fjava-api%237%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@b79d11cf-1a5a-4d28-94a7-6a09e9474515, thread: pool-670-thread-1
com.zerocracy.radars.github.ThrottledComments[76] java.lang.IllegalStateException: Can't post an identical message to zold-io/java-api#7: @llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue
```

[0.25.1](https://github.com/zerocracy/farm): Issue: zold-io/java-api#7, Action: `reopened`

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@b79d11cf-1a5a-4d28-94a7-6a09e9474515, thread: AsyncFlush-6
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 1 error(s) in XML document: -1:-1: Duplicate unique value [gh:zold-io/java-api#7] declared for identity constraint of element "verbosity".
```

[0.25.1](https://github.com/zerocracy/farm): CID: [1862352179](https://www.0crat.com/CAZUREFND/1862352179), Type: "Close job", Author: "llorllale"

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0crat** [comment]
The job [#7](https://github.com/zold-io/java-api/issues/7) is now out of scope
