### ISSUE TITLE
How to connect to network?

### ISSUE THREAD

**Issue by t-izbassar** [zold-io/java-api#8]
It's not clear how to connect to Zold network. Is there some `REST API` that we should use? Or there is some master address, and we need to issue some commands?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256), @llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@6ac9e0a3-eadb-45bf-b051-800033971ed4, thread: pool-293-thread-1
com.zerocracy.radars.github.ThrottledComments[76] java.lang.IllegalStateException: Can't post an identical message to zold-io/java-api#8: @yegor256[/z](https://www.0crat.com/u/yegor256), @llorllale[/z](https://www.0crat.com/u/llorllale) p
```

[0.24.9](https://github.com/zerocracy/farm): Issue: zold-io/java-api#8, Action: `opened`

**Comment by llorllale** [comment]
@t-izbassar refer to *RESTful API* in the [whitepaper](https://papers.zold.io/wp.pdf).

I've added a recommendation to read the whitepaper in the README (see b8913ff810063dd7f395e5be9d5fc44a5b450886).

Does this answer your questions?

**Comment by t-izbassar** [comment]
@llorllale the API part of the white paper is helpful. However, to what node we should connect? How to get the relevant node address? Is it enough to connect to the one node or we need to ask every node for information?

**Comment by llorllale** [comment]
@t-izbassar 

> to what node we should connect?

Depends on the activity. As per the whitepaper:

* Pull a wallet from all nodes that know about said wallet
* Pay taxes to the node with the highest score
* Push a wallet to "any" node of your choosing. That node will also then promote your wallet to all other nodes that it knows about (if your tax debt is < 1 ZLD)

**Comment by llorllale** [comment]
@t-izbassar 

> How to get the relevant node address?

As per the whitepaper, there is a default list of nodes defined [here](https://github.com/zold-io/zold/blob/master/resources/remotes). The REST API also defines a node endpoint that returns the list of all remote nodes that that node is currently aware of.

**Comment by t-izbassar** [comment]
@llorllale thanks for clarifications.

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@6ac9e0a3-eadb-45bf-b051-800033971ed4, thread: pool-813-thread-1
com.zerocracy.pm.Claims[122] java.lang.IllegalStateException: Duplicate claims are not allowed in [CAZUREFND](https://www.0crat.com/p/CAZUREFND), can't add this XML to 3 existing ones (Close job;{job=gh:zold-io/java-api#7, reason=GitHub issue was closed},Close job;{job=gh:zold-io/java-api#7, reason=GitHub issue was closed},Close job;{job=gh:zold-io/java-api#8, reason=GitHub issue was closed}):
<?xml version="1.0" encoding="UTF-8"?>
<claim id="1850507786">
   <created>2018-07-04T05:00:31.468Z</created>
   <type>Close job</type>
   <token>github;zold-io/java-api;8</token>
   <author>t-izbassar</author>
   <params>
      <param name="job">gh:zold-io/java-api#8</param>
      <param name="reason">GitHub issue was closed</param>
   </params>
   <until>2018-07-04T05:15:31.471Z</until>
</claim>

```

[0.24.9](https://github.com/zerocracy/farm): Issue: zold-io/java-api#8, Action: `closed`

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@6ac9e0a3-eadb-45bf-b051-800033971ed4, thread: pool-812-thread-1
com.zerocracy.pm.Claims[122] java.lang.IllegalStateException: Duplicate claims are not allowed in [CAZUREFND](https://www.0crat.com/p/CAZUREFND), can't add this XML to 4 existing ones (Close job;{job=gh:zold-io/java-api#7, reason=GitHub issue was closed},Close job;{job=gh:zold-io/java-api#7, reason=GitHub issue was closed},Close job;{job=gh:zold-io/java-api#8, reason=GitHub issue was closed},Close job;{job=gh:zold-io/java-api#8, reason=GitHub issue was closed}):
<?xml version="1.0" encoding="UTF-8"?>
<claim id="1850507791">
   <created>2018-07-04T05:00:37.984Z</created>
   <type>Close job</type>
   <token>github;zold-io/java-api;8</token>
   <author>t-izbassar</author>
   <params>
      <param name="job">gh:zold-io/java-api#8</param>
      <param name="reason">GitHub issue was closed</param>
   </params>
   <until>2018-07-04T05:15:37.987Z</until>
</claim>

```

[0.24.9](https://github.com/zerocracy/farm): Issue: zold-io/java-api#8, Action: `closed`

**Comment by 0crat** [comment]
Job `gh:zold-io/java-api#8` is not assigned, can't get performer

**Comment by 0crat** [comment]
Job `gh:zold-io/java-api#8` is not assigned, can't get performer
