### ISSUE TITLE
Let's update Copyright notice to 2019.

### ISSUE THREAD

**Issue by fabriciofx** [zold-io/java-api#87]
Let's update Copyright notice to 2019.

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment]
@fabriciofx[/z](https://www.0crat.com/u/fabriciofx) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CAZUREFND) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment]
@fabriciofx[/z](https://www.0crat.com/u/fabriciofx) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CAZUREFND) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by llorllale** [comment]
@fabriciofx I don't understand why we should be maintaining a range of dates for the copyright notice. As far as I am aware, the really important date is the one when the work was published (the start date). You *may* add a "revised date" to the notice if a file's contents changes "significantly", but do **we** really need to? Guava certainly doesn't do it. I'm guessing the hassle isn't worth it.

Sources:
* [Copyright.gov (PDF)](https://www.copyright.gov/circs/circ03.pdf)
* [StackOverflow](https://stackoverflow.com/questions/2390230/do-copyright-dates-need-to-be-updated)

**Comment by llorllale** [comment]
@yegor256 WDYT about dropping date ranges from the copyright notice and just leave the original publication date?

**Comment by fabriciofx** [comment]
@llorllale I agree with you. Let's wait for @yegor256 opinion. But let me know if you would like to close this issue and open another or just rename the title (and the others, like [cactoos/#985](https://github.com/yegor256/cactoos/issues/985), ok?

**Comment by 0crat** [comment]
Job `gh:zold-io/java-api#87` is not assigned, can't get performer
