### ISSUE TITLE
Introduce WalletMatcher

### ISSUE THREAD

**Issue by t-izbassar** [zold-io/java-api#9]
It will be useful for tests to have class `WalletMatcher`. It can be used as follows:
```java
MatcherAssert.assertThat(
    new WalletsIn(this.path).create(),
    WalletMatcher.hasId(id)
);
```

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256), @llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@6ac9e0a3-eadb-45bf-b051-800033971ed4, thread: pool-339-thread-1
com.zerocracy.radars.github.ThrottledComments[76] java.lang.IllegalStateException: Can't post an identical message to zold-io/java-api#9: @yegor256[/z](https://www.0crat.com/u/yegor256), @llorllale[/z](https://www.0crat.com/u/llorllale) p
```

[0.24.9](https://github.com/zerocracy/farm): Issue: zold-io/java-api#9, Action: `opened`

**Comment by llorllale** [comment]
@t-izbassar aside from the fact that we avoid static methods, I don't see the need for this...

**Comment by llorllale** [comment]
@t-izbassar I'm closing this because I don't see a use case for this now

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
